- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: sample ec2 key
    ec2_key:
      name: sample
      region: ap-southeast-1
    register: keyout
  - debug:
      var: keyout
  - name: store login key
    copy:
      content: "{{keyout.key.private_key}}"
      dest: ./sample_key.pem
    when: keyout.changed